### ISSUE TITLE
/clear with item tag is turned into a generic /clear

### ISSUE THREAD

**Issue by TheNuclearNexus** [mcbeet/beet#188]
# Problem
```
execute store result score @s smithed.data run clear @s #smithed:crafter/all 0
```
is converted to
```
execute store result score @s smithed.data run clear @s
```
# Details
This only seems to happen when using an item tag, setting the item to something like `cobblestone` removes the issue
# beet.yaml
```yml
name: Smithed Crafter
description: Native Library for Smithed
author: TheNuclearNexus
version: '0.0.2'

data_pack:
  name: Smithed Crafter
  load:
    - datapack
  render:
    functions:
      - smithed:*

output: out

require:
  - plugins.versioning
  - beet.contrib.dundervar

pipeline:
  - mecha

meta:
  mecha:
    keep_comments: true
```
