### ISSUE TITLE
ctx.data and ctx.assets are not populated by the config

### ISSUE THREAD

**Issue by BPR02** [mcbeet/beet#451]
In the `beet_default` of a custom plugin, the config values for `data_pack` and `resource_pack` are not inserted into the `ctx.data` and `ctx.assets` fields respectively. The config values are currently not available except for the internal plugin that generates the output (i.e. the `pack.mcmeta` file).

### Example:
`beet.yaml`
```yaml
data_pack:
  name: My Data Pack
  description: a data pack
  load: src
  pack_format: 6
  supported_formats: [0,6]

pipeline:
  - custom_plugin
```

`custom_plugin.py`
```py
def beet_default(ctx: Context):
  print(ctx.data.name)
  print(ctx.data.description)
  print(ctx.data.pack_format)
  print(ctx.data.supported_formats)
```

**Result**
This will print out the following (i.e. the default values):
```
None

48
None
```

**Expected**
The values should return the value set in the config:
```bash
My Data Pack
a data pack
6
[0, 6]
```
